const encode = (value: string) => encodeURIComponent(value);

export const endpoints = {
  auth: {
    me: "/api/auth/me",
    officerLogin: "/api/auth/officer/login",
    cadetRequestOtp: "/api/auth/cadet/request-otp",
    cadetVerifyOtp: "/api/auth/cadet/verify-otp",
    cadetVerifyFace: "/api/auth/cadet/verify-face",
    refresh: "/api/auth/refresh",
    logout: "/api/auth/logout",
    deleteAccount: "/api/auth/account",
  },
  stats: "/api/stats",
  auditLogs: "/api/audit-logs",
  dashboard: { live: "/api/dashboard/live", filter: (query = "") => `/api/dashboard/filter${query}` },
  device: { status: "/api/device/status", config: "/api/device/config" },
  notifications: {
    config: "/api/notifications/config",
    send: "/api/notifications/send",
    list: (query = "") => `/api/notifications${query}`,
    history: (query = "") => `/api/notifications/history${query}`,
    read: (id: string) => `/api/notifications/${encode(id)}/read`,
    archive: (id: string) => `/api/notifications/${encode(id)}/archive`,
    remove: (id: string) => `/api/notifications/${encode(id)}`,
    markAllRead: "/api/notifications/mark-all-read",
  },
  reports: {
    settings: "/api/reports/settings",
    daily: (query = "") => `/api/reports/daily${query}`,
    generate: "/api/reports/generate",
  },
  face: {
    validateFrame: "/api/cadets/validate-face-frame",
    enrollFace: "/api/cadets/enroll-face",
    enrollmentStatus: (cadetId: string) => `/api/face/enrollment-status/${encode(cadetId)}`,
  },
  leaveRequests: "/api/cadet/leave-request",
  cadet: {
    dashboard: "/api/cadet/dashboard",
    profile: "/api/cadet/dashboard",
    leaveRequests: "/api/cadet/dashboard",
    shoreLeaveRequest: "/api/cadet/shore-leave-request",
    sendGatePassEmail: "/api/cadet/send-gate-pass-email",
  },
  cadets: { byRoll: (roll: string) => `/api/cadets/${encode(roll)}` },
  gate: {
    checkIn: "/api/cadets/checkin",
    checkOut: "/api/cadets/checkout",
    scanStatus: "/api/cadets/scan-status",
    generateOtp: "/api/gate/otp/generate",
    verifyOtp: "/api/gate/otp/verify",
  },
  nfc: {
    status: "/api/nfc/status",
    scan: "/api/nfc/scan",
    cancel: "/api/nfc/cancel",
    register: "/api/nfc/register",
    replace: "/api/nfc/replace",
    remove: "/api/nfc/remove",
    verify: "/api/nfc/verify",
    tags: "/api/nfc/tags",
    tag: (cadetId: string) => `/api/nfc/tags/${encode(cadetId)}`,
    gateHistory: (query = "") => `/api/nfc/gate-history${query}`,
  },
  fingerprint: {
    deviceStatus: "/api/fingerprint/device/status",
    summary: "/api/fingerprint/summary",
    status: (cadetId: string) => `/api/fingerprint/status/${encode(cadetId)}`,
    enroll: "/api/fingerprint/enroll",
    verify: "/api/fingerprint/verify",
    reenroll: (cadetId: string) => `/api/fingerprint/reenroll/${encode(cadetId)}`,
    remove: (cadetId: string) => `/api/fingerprint/remove/${encode(cadetId)}`,
  },
  admin: {
    cadets: (query = "") => `/api/admin/cadets${query}`,
    cadet: (roll: string) => `/api/admin/cadets/${encode(roll)}`,
    cadetHistory: (roll: string) => `/api/admin/cadets/${encode(roll)}/history`,
    blockCadet: (roll: string) => `/api/admin/cadets/${encode(roll)}/block`,
    blockCadetLeave: (roll: string) => `/api/admin/cadets/${encode(roll)}/block-leave`,
    unblockCadetLeave: (roll: string) => `/api/admin/cadets/${encode(roll)}/unblock-leave`,
    importCadets: "/api/admin/import-cadets",
    leaveRequests: (query = "") => `/api/admin/leave-requests${query}`,
    decideLeave: (roll: string) => `/api/admin/leave-requests/${encode(roll)}/approve`,
    leaveTokenControl: "/api/admin/leave-token-control",
    leaveTokenAction: (roll: string, action: string) => `/api/admin/leave-token-control/${encode(roll)}/${encode(action)}`,
    officers: "/api/admin/officers",
    officerProvisionRequestOtp: "/api/admin/officers/provision/request-otp",
    officerProvisionConfirm: "/api/admin/officers/provision/confirm",
    faceEnrollmentStatus: "/api/admin/face-enrollment-status",
    faceEnrollmentReminder: (roll: string) => `/api/admin/face-enrollment-reminder/${encode(roll)}`,
    exportLeaveRecords: "/api/admin/export/leave-records",
    exportAuditLogs: "/api/admin/export/audit-logs",
  },
} as const;
