export const queryKeys = {
  auth: { me: ["auth", "me"] as const },
  admin: {
    profile: ["admin", "profile"] as const,
    summary: ["admin", "summary"] as const,
    cadets: ["admin", "cadets"] as const,
    outsideCadets: ["admin", "cadets", "outside"] as const,
    faceCadets: ["admin", "cadets", "face"] as const,
    fingerprintCadets: ["admin", "cadets", "fingerprint"] as const,
    fingerprintSummary: ["admin", "fingerprint-summary"] as const,
    fingerprintDevice: ["admin", "fingerprint-device"] as const,
    fingerprintStatus: (cadetId?: string) => ["admin", "fingerprint-status", cadetId] as const,
    nfcCadets: ["admin", "cadets", "nfc"] as const,
    nfcSummary: ["admin", "nfc-summary"] as const,
    leaveRequests: ["admin", "leave-requests"] as const,
    leaveTokenControl: ["admin", "leave-token-control"] as const,
    pendingCheckout: ["admin", "pending-checkout"] as const,
    leaveStatus: ["admin", "leave-status"] as const,
    gateEvents: ["admin", "gate-events"] as const,
    checkInLog: ["admin", "checkin-log"] as const,
    gateHistory: ["admin", "gate-history"] as const,
    reportSettings: ["admin", "report-settings"] as const,
    dailyReports: ["admin", "daily-reports"] as const,
    returnMonitor: ["admin", "return-monitor"] as const,
    branchSummary: ["admin", "branch-summary"] as const,
    notifications: ["admin", "notifications"] as const,
  },
  cadet: {
    profile: (userId?: string) => ["cadet", "profile", userId] as const,
    leaveRequests: (cadetId?: string) => ["cadet", "leave-requests", cadetId] as const,
    notifications: ["cadet", "notifications"] as const,
  },
} as const;
